-- "Pengajuan Voucher" Petty Cash - tahap SETELAH sebuah Input Pengajuan
-- (petty_cash_pengajuan, lihat petty-cash-pengajuan-setup.sql) selesai
-- di-approve. Satu Voucher = SNAPSHOT persis dari satu Pengajuan yang sudah
-- berstatus "Approved" (item/qty/harga/catatan/lampiran di-copy apa adanya,
-- tidak bisa diubah requester) - karena itu `pengajuan_id` UNIQUE, satu
-- Pengajuan cuma boleh dipakai untuk SATU Voucher.
--
-- Jalur approval-nya sendiri (auto-terapkan dari Template Approval dengan
-- approval_type = "Approval Voucher", lihat resolvePcAutoTemplate di
-- services/pcApprovalTemplateService.ts) TERPISAH dari jalur approval
-- Pengajuan-nya - keduanya bisa beda approver/beda departemen tujuan sama
-- sekali.
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama), SETELAH
-- petty-cash-pengajuan-setup.sql & pc-approval-template-approval-type-setup.sql.

create table if not exists public.petty_cash_voucher (
  id bigint generated by default as identity primary key,
  kode_voucher text not null unique,
  pengajuan_id bigint not null references public.petty_cash_pengajuan(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete cascade,
  company_code text not null,
  department text not null,
  cost_center_id bigint references public.cost_centers(id) on delete set null,
  needed_date date not null,
  notes text default '',
  -- Snapshot dari items Pengajuan asalnya - lihat komentar di atas.
  items jsonb not null default '[]',
  total_amount numeric not null default 0,
  attachments jsonb default '[]',
  status text not null default 'In Approval',
  approvals jsonb not null default '[]',
  discussions jsonb default '[]',
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null,
  constraint petty_cash_voucher_pengajuan_id_key unique (pengajuan_id)
);

create index if not exists idx_petty_cash_voucher_user_id
  on public.petty_cash_voucher (user_id);
create index if not exists idx_petty_cash_voucher_company_code
  on public.petty_cash_voucher (company_code);

create or replace function public.handle_petty_cash_voucher_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists on_petty_cash_voucher_write on public.petty_cash_voucher;
create trigger on_petty_cash_voucher_write
  before insert or update on public.petty_cash_voucher
  for each row execute function public.handle_petty_cash_voucher_audit();

alter table public.petty_cash_voucher enable row level security;

-- Baca: dibuka utk semua user login, sama seperti petty_cash_pengajuan
-- (dibutuhkan approver/GA/Finance lintas departemen di tahap lanjutannya).
drop policy if exists "petty_cash_voucher_select" on public.petty_cash_voucher;
create policy "petty_cash_voucher_select"
  on public.petty_cash_voucher
  for select
  to authenticated
  using (true);

-- Insert: cuma boleh atas nama diri sendiri, company/department harus sesuai
-- profile-nya sendiri (sama seperti petty_cash_pengajuan_insert), DAN
-- pengajuan_id yang direferensikan wajib: (1) benar-benar Pengajuan milik
-- pemohon yang sama, dan (2) statusnya sudah "Approved" - jaminan level DB
-- di atas pengecekan yang sama di createVoucherFromPengajuan
-- (services/pettyCashVoucherService.ts), bukan pengganti pengecekan itu.
drop policy if exists "petty_cash_voucher_insert" on public.petty_cash_voucher;
create policy "petty_cash_voucher_insert"
  on public.petty_cash_voucher
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.company = petty_cash_voucher.company_code
        and p.department = petty_cash_voucher.department
    )
    and exists (
      select 1 from public.petty_cash_pengajuan pj
      where pj.id = petty_cash_voucher.pengajuan_id
        and pj.user_id = auth.uid()
        and pj.status = 'Approved'
    )
  );

-- Update: approver yang ada di `approvals` dengan status "pending" - sama
-- persis idiomnya dengan petty_cash_pengajuan_update_approver, lihat
-- petty-cash-pengajuan-approval-setup.sql untuk penjelasan lengkapnya
-- (containment jsonb, urutan approval tetap divalidasi di app lewat
-- isMyApprovalTurn, lib/pcApprovalFlow.ts).
drop policy if exists "petty_cash_voucher_update_approver" on public.petty_cash_voucher;
create policy "petty_cash_voucher_update_approver"
  on public.petty_cash_voucher
  for update
  to authenticated
  using (
    approvals @> jsonb_build_array(
      jsonb_build_object('userid', auth.uid()::text, 'status', 'pending')
    )
  )
  with check (true);
