-- SUB-VOUCHER Petty Cash - tabel `petty_cash_sub_voucher`, tarikan dana
-- PARSIAL dari sebuah Voucher yang sudah full-approved (lihat komentar
-- PettyCashSubVoucher di type/index.ts) - MENGGANTIKAN alur klaim sekali-
-- penuh yang lama (submitVoucherClaim/"Permintaan Klaim", sudah dihapus).
-- Voucher tetap berstatus "Approved" selama masih bisa ditarik, baru jadi
-- "Selesai" begitu SEMUA sub-voucher sudah dideklarasikan & disetujui DAN
-- totalnya sudah menutup total_amount Voucher (lihat rewrite trigger di
-- petty-cash-voucher-deklarasi-complete-setup.sql).
--
-- TIDAK ADA policy INSERT langsung ke tabel ini SENGAJA - satu-satunya jalan
-- masuk adalah RPC create_petty_cash_sub_voucher di bawah (SECURITY
-- DEFINER), supaya validasi sisa Voucher & potong budget SELALU atomic
-- dalam satu transaksi (race-safe kalau ada 2 tarikan hampir bersamaan).
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama), SETELAH
-- petty-cash-voucher-setup.sql, petty-cash-budget-setup.sql, &
-- petty-cash-pengajuan-budget-setup.sql.

create table if not exists public.petty_cash_sub_voucher (
  -- Identity cuma fallback - createSubVoucher
  -- (services/pettyCashSubVoucherService.ts) SELALU kirim id acak 7 digit
  -- sendiri (generateRandomId, lib/utils.ts), sama alasannya dengan
  -- petty_cash_pengajuan/voucher/deklarasi.
  id bigint generated by default as identity primary key,
  kode_sub_voucher text not null unique,
  voucher_id bigint not null references public.petty_cash_voucher(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric not null,
  notes text default '',
  status text not null default 'Aktif',
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists idx_petty_cash_sub_voucher_voucher_id
  on public.petty_cash_sub_voucher (voucher_id);
create index if not exists idx_petty_cash_sub_voucher_user_id
  on public.petty_cash_sub_voucher (user_id);

create or replace function public.handle_petty_cash_sub_voucher_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists on_petty_cash_sub_voucher_write on public.petty_cash_sub_voucher;
create trigger on_petty_cash_sub_voucher_write
  before insert or update on public.petty_cash_sub_voucher
  for each row execute function public.handle_petty_cash_sub_voucher_audit();

alter table public.petty_cash_sub_voucher enable row level security;

-- Baca: dibuka utk semua user login, sama seperti petty_cash_voucher
-- (approver/GA/Finance lintas departemen butuh lihat riwayat tarikan).
drop policy if exists "petty_cash_sub_voucher_select" on public.petty_cash_sub_voucher;
create policy "petty_cash_sub_voucher_select"
  on public.petty_cash_sub_voucher
  for select
  to authenticated
  using (true);

-- SENGAJA TIDAK ADA policy INSERT/UPDATE/DELETE - satu-satunya jalan masuk
-- baris baru adalah lewat RPC di bawah (SECURITY DEFINER, bypass RLS).

-- Tarikan dana atomic - satu transaksi memvalidasi SEKALIGUS memotong,
-- supaya dua tarikan yang hampir bersamaan tidak bisa sama-sama lolos cek
-- "sisa cukup" lalu berdua memotong lebih dari yang tersedia (race
-- condition kalau dilakukan read-then-write biasa dari client).
create or replace function public.create_petty_cash_sub_voucher(
  p_id bigint,
  p_kode_sub_voucher text,
  p_voucher_id bigint,
  p_amount numeric,
  p_notes text
)
returns public.petty_cash_sub_voucher
language plpgsql
security definer
set search_path = public
as $$
declare
  v_voucher public.petty_cash_voucher%rowtype;
  v_drawn numeric;
  v_remaining_voucher numeric;
  v_new_budget numeric;
  v_row public.petty_cash_sub_voucher%rowtype;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'Nominal tarikan harus lebih dari 0.';
  end if;

  select * into v_voucher from public.petty_cash_voucher where id = p_voucher_id for update;
  if not found then
    raise exception 'Voucher tidak ditemukan.';
  end if;
  if v_voucher.user_id <> auth.uid() then
    raise exception 'Anda bukan pemilik Voucher ini.';
  end if;
  if v_voucher.status <> 'Approved' then
    raise exception 'Voucher belum/sudah tidak berstatus Approved, tidak bisa ditarik.';
  end if;
  if v_voucher.budget_id is null then
    raise exception 'Voucher ini belum punya Budget yang ditetapkan - hubungi GA/Admin.';
  end if;

  select coalesce(sum(amount), 0) into v_drawn
  from public.petty_cash_sub_voucher
  where voucher_id = p_voucher_id;

  v_remaining_voucher := v_voucher.total_amount - v_drawn;
  if p_amount > v_remaining_voucher then
    raise exception 'Nominal tarikan melebihi sisa Voucher (sisa Rp%).', v_remaining_voucher;
  end if;

  update public.petty_cash_budget
  set current_budget = current_budget - p_amount
  where id = v_voucher.budget_id
    and current_budget >= p_amount
  returning current_budget into v_new_budget;

  if v_new_budget is null then
    raise exception 'Sisa budget departemen tidak mencukupi untuk tarikan ini.';
  end if;

  insert into public.petty_cash_sub_voucher (id, kode_sub_voucher, voucher_id, user_id, amount, notes)
  values (p_id, p_kode_sub_voucher, p_voucher_id, auth.uid(), p_amount, p_notes)
  returning * into v_row;

  insert into public.petty_cash_budget_history (
    budget_id, ref_type, ref_id, user_id, change_amount, previous_budget, new_budget, description
  ) values (
    v_voucher.budget_id, 'deduction', v_row.id, auth.uid(), -p_amount,
    v_new_budget + p_amount, v_new_budget,
    'Tarikan Sub-Voucher ' || p_kode_sub_voucher
  );

  return v_row;
end;
$$;

grant execute on function public.create_petty_cash_sub_voucher(bigint, text, bigint, numeric, text) to authenticated;
