-- "Template Pengajuan" Petty Cash - tabel `petty_cash_pengajuan_template`,
-- daftar barang siap pakai milik SATU user (PER-USER, bukan katalog bersama
-- seperti petty_cash_barang) untuk kebutuhan yang bisa diprediksi & relatif
-- konstan (mis. "ATK Bulanan") - dipakai supaya requester tidak input ulang
-- barang yang sama tiap kali submit Input Pengajuan, cuma beda tanggal/
-- minggu dibutuhkan. Lihat PettyCashPengajuanTemplateClient.tsx (kelola
-- template) & InputPengajuanClient.tsx (terapkan template lewat
-- ?template=<id>).
--
-- Item di sini SENGAJA tidak menyimpan `coa` yang valid (di-reset ke COA
-- yang berlaku SAAT template diterapkan, bukan disimpan) - requester bisa
-- pindah company/COA antar waktu, jadi COA harus diresolusi ulang tiap kali
-- template dipakai, bukan dibekukan dari saat template dibuat.
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama).

create table if not exists public.petty_cash_pengajuan_template (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  nama_template text not null,
  items jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_petty_cash_pengajuan_template_user_id
  on public.petty_cash_pengajuan_template (user_id);

create or replace function public.handle_petty_cash_pengajuan_template_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.user_id := old.user_id;
    new.updated_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists on_petty_cash_pengajuan_template_write on public.petty_cash_pengajuan_template;
create trigger on_petty_cash_pengajuan_template_write
  before insert or update on public.petty_cash_pengajuan_template
  for each row execute function public.handle_petty_cash_pengajuan_template_audit();

alter table public.petty_cash_pengajuan_template enable row level security;

-- Murni per-user - beda dari dokumen approval (petty_cash_pengajuan dkk.)
-- yang select-nya dibuka ke semua user login, template ini privat milik
-- pembuatnya sendiri (tidak ada approver/admin yang perlu ikut melihat).
drop policy if exists "petty_cash_pengajuan_template_select" on public.petty_cash_pengajuan_template;
create policy "petty_cash_pengajuan_template_select"
  on public.petty_cash_pengajuan_template
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "petty_cash_pengajuan_template_insert" on public.petty_cash_pengajuan_template;
create policy "petty_cash_pengajuan_template_insert"
  on public.petty_cash_pengajuan_template
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "petty_cash_pengajuan_template_update" on public.petty_cash_pengajuan_template;
create policy "petty_cash_pengajuan_template_update"
  on public.petty_cash_pengajuan_template
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "petty_cash_pengajuan_template_delete" on public.petty_cash_pengajuan_template;
create policy "petty_cash_pengajuan_template_delete"
  on public.petty_cash_pengajuan_template
  for delete
  to authenticated
  using (user_id = auth.uid());
