-- "Budgeting" Petty Cash (GA/Admin only) - tabel `petty_cash_budget`, pool
-- budget PER DEPARTEMEN (bukan per company/COA - lihat komentar
-- PettyCashBudget di type/index.ts) yang AUTO-terisi ke Pengajuan baru
-- sesuai departemen requester (resolveAutoBudget,
-- services/pettyCashBudgetService.ts - mirip resolvePcAutoTemplate),
-- approver Pengajuan boleh ganti lewat "Edit & Setujui".
--
-- Pola CRUD & riwayat top-up-nya SENGAJA dibuat identik dengan
-- cost_centers/cost_center_history (punya MR/PO) supaya konsisten, tapi
-- tabelnya TERPISAH - budget Petty Cash butuh auto-resolve by department &
-- auto-potong saat sub-voucher ditarik (lihat
-- petty-cash-sub-voucher-setup.sql), yang tidak dipunyai cost center MR/PO
-- (murni manual top-up, tidak pernah otomatis berkurang).
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama).

create table if not exists public.petty_cash_budget (
  id bigint generated by default as identity primary key,
  name text not null,
  department text not null,
  initial_budget numeric not null default 0,
  current_budget numeric not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

-- Satu departemen maksimal SATU budget AKTIF sekaligus (partial unique
-- index - baris yang dinonaktifkan tetap boleh menumpuk sebagai riwayat,
-- sama seperti cost_centers yang tidak pernah dihapus, cuma dinonaktifkan)
-- - mirip aturan "satu departemen satu template approval auto" di
-- pc_approval_template_auto_rules, supaya resolveAutoBudget selalu unambigu.
create unique index if not exists idx_petty_cash_budget_department_active
  on public.petty_cash_budget (department)
  where is_active;

create index if not exists idx_petty_cash_budget_department
  on public.petty_cash_budget (department);

create table if not exists public.petty_cash_budget_history (
  id bigint generated by default as identity primary key,
  budget_id bigint not null references public.petty_cash_budget(id) on delete cascade,
  -- 'initial' (saat budget dibuat), 'topup'/'adjustment' (Edit/Top-up admin
  -- manual), 'deduction' (otomatis saat sub-voucher ditarik - ref_id =
  -- petty_cash_sub_voucher.id), 'deactivate' (audit nonaktifkan/aktifkan,
  -- change_amount = 0).
  ref_type text not null,
  ref_id bigint,
  user_id uuid references public.profiles(id) on delete set null,
  change_amount numeric not null,
  previous_budget numeric not null,
  new_budget numeric not null,
  description text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_petty_cash_budget_history_budget_id
  on public.petty_cash_budget_history (budget_id);

create or replace function public.handle_petty_cash_budget_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists on_petty_cash_budget_write on public.petty_cash_budget;
create trigger on_petty_cash_budget_write
  before insert or update on public.petty_cash_budget
  for each row execute function public.handle_petty_cash_budget_audit();

alter table public.petty_cash_budget enable row level security;
alter table public.petty_cash_budget_history enable row level security;

-- Baca: dibuka utk semua user login - requester perlu lihat nama & sisa
-- budget yang otomatis kepasang di Pengajuan-nya (sama pola dengan
-- cost_centers yang juga dibuka luas utk keperluan tampilan).
drop policy if exists "petty_cash_budget_select" on public.petty_cash_budget;
create policy "petty_cash_budget_select"
  on public.petty_cash_budget
  for select
  to authenticated
  using (true);

drop policy if exists "petty_cash_budget_history_select" on public.petty_cash_budget_history;
create policy "petty_cash_budget_history_select"
  on public.petty_cash_budget_history
  for select
  to authenticated
  using (true);

-- Kelola (insert/update/delete): GA/Admin saja - pola SAMA PERSIS dengan
-- petty_cash_barang & pc_approval_templates (lihat
-- petty-cash-barang-setup.sql / pc-approval-templates-access-setup.sql).
drop policy if exists "petty_cash_budget_insert" on public.petty_cash_budget;
create policy "petty_cash_budget_insert"
  on public.petty_cash_budget
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  );

drop policy if exists "petty_cash_budget_update" on public.petty_cash_budget;
create policy "petty_cash_budget_update"
  on public.petty_cash_budget
  for update
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  );

-- Insert ke history: GA/Admin (aksi manual lewat halaman Budgeting) DAN
-- lewat RPC create_petty_cash_sub_voucher (SECURITY DEFINER, bypass RLS
-- otomatis - lihat petty-cash-sub-voucher-setup.sql) utk ref_type
-- 'deduction'. Policy ini cuma melayani jalur manual GA/Admin.
drop policy if exists "petty_cash_budget_history_insert" on public.petty_cash_budget_history;
create policy "petty_cash_budget_history_insert"
  on public.petty_cash_budget_history
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  );
