-- "Deklarasi" Petty Cash - tahap SETELAH sebuah Voucher (petty_cash_voucher,
-- lihat petty-cash-voucher-setup.sql) diajukan klaim pencairannya
-- ("Permintaan Klaim", lihat submitVoucherClaim,
-- services/pettyCashVoucherService.ts). Requester melaporkan pemakaian RIIL
-- dana yang sudah dicairkan lewat /petty-cash/deklarasi - karena itu
-- `voucher_id` UNIQUE, satu Voucher cuma boleh dipakai untuk SATU Deklarasi.
--
-- BEDA dari Voucher (snapshot APA ADANYA dari Pengajuan): item Deklarasi
-- disalin dari Voucher asalnya TAPI qty/unit_price/note per baris BOLEH
-- disesuaikan requester ke pemakaian riil (struk asli kadang beda dari
-- rencana) - lihat createDeklarasiFromVoucher,
-- services/pettyCashDeklarasiService.ts.
--
-- Jalur approval-nya sendiri (auto-terapkan dari Template Approval dengan
-- approval_type = "Approval Deklarasi", lihat resolvePcAutoTemplate di
-- services/pcApprovalTemplateService.ts) TERPISAH dari jalur approval
-- Voucher-nya.
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama), SETELAH
-- petty-cash-voucher-setup.sql & petty-cash-voucher-claim-setup.sql.

create table if not exists public.petty_cash_deklarasi (
  id bigint generated by default as identity primary key,
  kode_deklarasi text not null unique,
  voucher_id bigint not null references public.petty_cash_voucher(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete cascade,
  company_code text not null,
  department text not null,
  cost_center_id bigint references public.cost_centers(id) on delete set null,
  notes text default '',
  -- Item aktual - disalin dari items Voucher asalnya, qty/unit_price/note
  -- boleh disesuaikan ke pemakaian riil (lihat komentar di atas file ini).
  items jsonb not null default '[]',
  total_amount numeric not null default 0,
  -- Bukti struk/nota asli - opsional (sama seperti attachments di
  -- petty_cash_pengajuan, bukan wajib di level DB/app).
  attachments jsonb default '[]',
  status text not null default 'In Approval',
  approvals jsonb not null default '[]',
  discussions jsonb default '[]',
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null,
  constraint petty_cash_deklarasi_voucher_id_key unique (voucher_id)
);

create index if not exists idx_petty_cash_deklarasi_user_id
  on public.petty_cash_deklarasi (user_id);
create index if not exists idx_petty_cash_deklarasi_company_code
  on public.petty_cash_deklarasi (company_code);

create or replace function public.handle_petty_cash_deklarasi_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists on_petty_cash_deklarasi_write on public.petty_cash_deklarasi;
create trigger on_petty_cash_deklarasi_write
  before insert or update on public.petty_cash_deklarasi
  for each row execute function public.handle_petty_cash_deklarasi_audit();

alter table public.petty_cash_deklarasi enable row level security;

-- Baca: dibuka utk semua user login, sama seperti petty_cash_voucher
-- (dibutuhkan approver/GA/Finance lintas departemen di tahap approval-nya).
drop policy if exists "petty_cash_deklarasi_select" on public.petty_cash_deklarasi;
create policy "petty_cash_deklarasi_select"
  on public.petty_cash_deklarasi
  for select
  to authenticated
  using (true);

-- Insert: cuma boleh atas nama diri sendiri, company/department harus sesuai
-- profile-nya sendiri (sama seperti petty_cash_voucher_insert), DAN
-- voucher_id yang direferensikan wajib: (1) benar-benar Voucher milik
-- pemohon yang sama, dan (2) statusnya sudah "Permintaan Klaim" - jaminan
-- level DB di atas pengecekan yang sama di createDeklarasiFromVoucher
-- (services/pettyCashDeklarasiService.ts), bukan pengganti pengecekan itu.
drop policy if exists "petty_cash_deklarasi_insert" on public.petty_cash_deklarasi;
create policy "petty_cash_deklarasi_insert"
  on public.petty_cash_deklarasi
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.company = petty_cash_deklarasi.company_code
        and p.department = petty_cash_deklarasi.department
    )
    and exists (
      select 1 from public.petty_cash_voucher v
      where v.id = petty_cash_deklarasi.voucher_id
        and v.user_id = auth.uid()
        and v.status = 'Permintaan Klaim'
    )
  );

-- Update: approver yang ada di `approvals` dengan status "pending" - sama
-- persis idiomnya dengan petty_cash_voucher_update_approver, lihat
-- petty-cash-pengajuan-approval-setup.sql untuk penjelasan lengkapnya
-- (containment jsonb, urutan approval tetap divalidasi di app lewat
-- isMyApprovalTurn, lib/pcApprovalFlow.ts).
drop policy if exists "petty_cash_deklarasi_update_approver" on public.petty_cash_deklarasi;
create policy "petty_cash_deklarasi_update_approver"
  on public.petty_cash_deklarasi
  for update
  to authenticated
  using (
    approvals @> jsonb_build_array(
      jsonb_build_object('userid', auth.uid()::text, 'status', 'pending')
    )
  )
  with check (true);
