-- Master data "Barang Petty Cash" - katalog barang KHUSUS petty cash, terpisah
-- total dari tabel `barang` (dipakai MR/PO utama). Sengaja dipisah supaya
-- perubahan/hapus di satu sisi tidak pernah menyentuh sisi lain.
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama saja - fitur ini
-- murni data, tidak menyentuh storage VPS).

create table if not exists public.petty_cash_barang (
  id bigint generated by default as identity primary key,
  part_number text,
  part_name text not null,
  category text,
  uom text,
  vendor text,
  last_purchase_price numeric default 0,
  link text,
  description text default '',
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

-- part_number opsional (banyak item petty cash - "Konsumsi Rapat", dsb - tidak
-- punya kode part formal), tapi kalau diisi harus unik. Partial unique index
-- supaya banyak baris NULL/'' tidak saling bentrok.
create unique index if not exists petty_cash_barang_part_number_key
  on public.petty_cash_barang (part_number)
  where part_number is not null and part_number <> '';

create index if not exists idx_petty_cash_barang_category
  on public.petty_cash_barang (category);

-- created_by/updated_by di-set otomatis dari sesi (auth.uid()), BUKAN dari
-- payload client - supaya tidak bisa dipalsukan dan konsisten dengan
-- updated_at (tidak perlu dikirim dari form sama sekali, lihat
-- services/pettyCashBarangService.ts).
create or replace function public.handle_petty_cash_barang_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists on_petty_cash_barang_write on public.petty_cash_barang;
create trigger on_petty_cash_barang_write
  before insert or update on public.petty_cash_barang
  for each row execute function public.handle_petty_cash_barang_audit();

alter table public.petty_cash_barang enable row level security;

-- Baca: semua user login boleh (dipakai saat memilih barang di form
-- pengajuan petty cash nantinya) - yang dibatasi cuma TULIS-nya.
drop policy if exists "petty_cash_barang_select" on public.petty_cash_barang;
create policy "petty_cash_barang_select"
  on public.petty_cash_barang
  for select
  to authenticated
  using (true);

-- Tulis (insert/update/delete): admin ATAU departemen setara GA. Daftar
-- departemen di bawah HARUS disamakan manual dengan GA_DEPARTMENTS di
-- lib/constants/departments.ts kalau nanti departemen itu berubah - SQL tidak
-- bisa import konstanta TypeScript.
drop policy if exists "petty_cash_barang_insert" on public.petty_cash_barang;
create policy "petty_cash_barang_insert"
  on public.petty_cash_barang
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  );

drop policy if exists "petty_cash_barang_update" on public.petty_cash_barang;
create policy "petty_cash_barang_update"
  on public.petty_cash_barang
  for update
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  );

drop policy if exists "petty_cash_barang_delete" on public.petty_cash_barang;
create policy "petty_cash_barang_delete"
  on public.petty_cash_barang
  for delete
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.department in ('General Affair', 'HRGA-HSE'))
    )
  );
