-- "Input Pengajuan" Petty Cash - alur BARU berbasis item (pakai katalog
-- petty_cash_barang), terpisah TOTAL dari petty_cash_requests (alur lama,
-- lump-sum Reimbursement/Cash Advance). Bagian dari rangkaian
-- Pengajuan -> Approval Pengajuan -> Pengajuan Voucher -> Approval Voucher ->
-- Claim Voucher -> Deklarasi -> Approval Deklarasi di menu sidebar Petty Cash
-- (tahap-tahap setelah Pengajuan belum dibuat, `status` sengaja dibiarkan
-- text bebas - bukan check constraint - supaya gampang ditambah nanti tanpa
-- migrasi, sama seperti material_requests/purchase_orders/petty_cash_requests).
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama).

create table if not exists public.petty_cash_pengajuan (
  id bigint generated by default as identity primary key,
  kode_pengajuan text not null unique,
  user_id uuid not null references public.profiles(id) on delete cascade,
  company_code text not null,
  department text not null,
  cost_center_id bigint references public.cost_centers(id) on delete set null,
  needed_date date not null,
  notes text default '',
  -- Array item: {barang_id: number|null, part_name, category, uom, qty,
  -- unit_price, subtotal, note}. barang_id null = barang manual (tidak ada
  -- di katalog petty_cash_barang).
  items jsonb not null default '[]',
  total_amount numeric not null default 0,
  attachments jsonb default '[]',
  status text not null default 'In Approval',
  approvals jsonb not null default '[]',
  discussions jsonb default '[]',
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists idx_petty_cash_pengajuan_user_id
  on public.petty_cash_pengajuan (user_id);
create index if not exists idx_petty_cash_pengajuan_company_code
  on public.petty_cash_pengajuan (company_code);

create or replace function public.handle_petty_cash_pengajuan_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists on_petty_cash_pengajuan_write on public.petty_cash_pengajuan;
create trigger on_petty_cash_pengajuan_write
  before insert or update on public.petty_cash_pengajuan
  for each row execute function public.handle_petty_cash_pengajuan_audit();

alter table public.petty_cash_pengajuan enable row level security;

-- Baca: dibuka utk semua user login (dibutuhkan approver/GA/Finance buat
-- proses lanjutannya, sama seperti petty_cash_requests lama - proteksi lebih
-- rinci per approver/tahap ditambahkan nanti bareng halaman Approval
-- Pengajuan dkk).
drop policy if exists "petty_cash_pengajuan_select" on public.petty_cash_pengajuan;
create policy "petty_cash_pengajuan_select"
  on public.petty_cash_pengajuan
  for select
  to authenticated
  using (true);

-- Insert: siapa saja boleh submit, TAPI cuma boleh atas nama diri sendiri &
-- company/department harus sesuai profile-nya sendiri (bukan bebas isi
-- apapun dari client).
--
-- PENTING: `profiles.department` punya nama kolom yang SAMA dengan
-- `petty_cash_pengajuan.department` - kalau ditulis tanpa qualifier eksplisit
-- (mis. `p.department = department`), Postgres resolve `department` yang
-- bare itu ke scope subquery TERDEKAT (profiles.department), bukan ke baris
-- baru yang mau di-insert - jadinya `p.department = p.department` yang
-- SELALU TRUE dan sama sekali tidak memvalidasi apapun. Makanya kolom baris
-- baru di sini WAJIB di-qualify pakai nama tabelnya (petty_cash_pengajuan.*).
drop policy if exists "petty_cash_pengajuan_insert" on public.petty_cash_pengajuan;
create policy "petty_cash_pengajuan_insert"
  on public.petty_cash_pengajuan
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.company = petty_cash_pengajuan.company_code
        and p.department = petty_cash_pengajuan.department
    )
  );

-- SENGAJA belum ada policy UPDATE/DELETE - belum ada fitur yang butuh
-- (approve/reject/voucher/klaim/deklarasi belum dibangun). Tambahkan
-- policy-nya di setup script terpisah begitu fitur itu dibuat, scoped ke
-- siapa yang benar-benar boleh update di tahap itu (mis. approver yang
-- namanya ada di approvals dgn status pending).
