-- Web Push Notification - tabel `push_subscriptions` menyimpan Push API
-- subscription per device/browser (endpoint + keys p256dh/auth) supaya
-- server bisa kirim notifikasi OS-level walau browser/tab user SUDAH
-- DITUTUP (beda dari notifikasi in-app biasa yang cuma jalan selagi tab
-- terbuka, lihat components/providers/NotificationProvider.tsx).
--
-- Satu user bisa punya banyak baris (1 per device/browser yang subscribe).
-- Dikonsumsi oleh app/api/push/send/route.ts (server-only, pakai
-- SUPABASE_SERVICE_ROLE_KEY - bypass RLS di bawah) tiap kali ada notifikasi
-- baru (lihat dispatchPushChannel, lib/notifications/client.ts).
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama).

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists idx_push_subscriptions_user_id
  on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

-- Select: user cuma lihat subscription miliknya sendiri (buat cek status
-- "aktif di device ini" - server kirim push pakai service_role, bypass RLS).
drop policy if exists "push_subscriptions_select_own" on public.push_subscriptions;
create policy "push_subscriptions_select_own"
  on public.push_subscriptions
  for select
  to authenticated
  using (user_id = auth.uid());

-- Insert/update: cuma atas nama diri sendiri. UPDATE dibutuhkan buat upsert
-- (onConflict: endpoint) kalau device yang sama subscribe ulang - misal
-- browser yang sama sebelumnya dipakai user lain (logout/login gonta-ganti
-- akun di device bersama).
drop policy if exists "push_subscriptions_insert_own" on public.push_subscriptions;
create policy "push_subscriptions_insert_own"
  on public.push_subscriptions
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "push_subscriptions_update_own" on public.push_subscriptions;
create policy "push_subscriptions_update_own"
  on public.push_subscriptions
  for update
  to authenticated
  using (true)
  with check (user_id = auth.uid());

-- Delete: unsubscribe (cuma milik sendiri).
drop policy if exists "push_subscriptions_delete_own" on public.push_subscriptions;
create policy "push_subscriptions_delete_own"
  on public.push_subscriptions
  for delete
  to authenticated
  using (user_id = auth.uid());
