-- Seed data: Barang Petty Cash
-- Generated from "Nama barang (Pettycash) (1).xlsx" — 167 items
-- Kode part_number format: PC-<KATEGORI_SINGKATAN>-<urutan per kategori>
-- last_purchase_price sengaja tidak diisi, pakai default kolom (0)
-- vendor NULL = vendor tidak tercantum di data sumber

insert into public.petty_cash_barang
  (part_number, part_name, category, uom, vendor)
values
  ('PC-BBM-1', 'Blindvan B 9282 KRW', 'BBM', 'Hari', 'SPBU'),
  ('PC-ETOL-1', 'Blindvan B 9282 KRW', 'E-Tol', 'Hari', 'Indomaret'),
  ('PC-BBM-2', 'Terios B 2338 KRJ', 'BBM', 'Hari', 'SPBU'),
  ('PC-ETOL-2', 'Terios B 2338 KRJ', 'E-Tol', 'Hari', 'Indomaret'),
  ('PC-BBM-3', 'Pickup B 9255 KAT', 'BBM', 'Hari', 'SPBU'),
  ('PC-ETOL-3', 'Pickup B 9255 KAT', 'E-Tol', 'Hari', 'Indomaret'),
  ('PC-BBM-4', 'Zenix B 1909 KKA', 'BBM', 'Hari', 'BP AKR'),
  ('PC-ETOL-4', 'Zenix B 1909 KKA', 'E-Tol', 'Hari', 'Indomaret'),
  ('PC-BBM-5', 'Alphard B 126 GMI', 'BBM', 'Hari', 'BP AKR'),
  ('PC-ETOL-5', 'Alphard B 126 GMI', 'E-Tol', 'Hari', 'Indomaret'),
  ('PC-OPS-1', 'Parkir blindvan B 9282 KRW', 'Operasional', 'Minggu', 'Parkir liar dan pak ogah'),
  ('PC-OPS-2', 'Parkir Terios B 2338 KRJ', 'Operasional', 'Minggu', 'Parkir liar dan pak ogah'),
  ('PC-OPS-3', 'Parkir Pickup B 9255 KAT', 'Operasional', 'Minggu', 'Parkir liar dan pak ogah'),
  ('PC-BBM-6', 'Luxio B 2477 KRG', 'BBM', 'Minggu', NULL),
  ('PC-BBM-7', 'Luxio B 2479 KRG', 'BBM', 'Minggu', NULL),
  ('PC-BBM-8', 'Grandmax B 2398 KIO', 'BBM', 'Minggu', NULL),
  ('PC-ETOL-6', 'Luxio B 2477 KRG', 'E-Tol', 'Minggu', NULL),
  ('PC-ETOL-7', 'Luxio B 2479 KRG', 'E-Tol', 'Minggu', NULL),
  ('PC-ETOL-8', 'Grandmax B 2398 KIO', 'E-Tol', 'Minggu', NULL),
  ('PC-BBM-9', 'Kendaraan OB', 'BBM', 'Minggu', NULL),
  ('PC-OPS-4', 'BBM Genset', 'Operasional', 'Minggu', NULL),
  ('PC-KD-1', 'Gula 1kg', 'Kebutuhan Dapur', 'Kg', NULL),
  ('PC-KD-2', 'Kopi Hitam kapal api 150gr', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-3', 'Tea Sariwangi isi 50', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-4', 'Tisue Roll', 'Kebutuhan Dapur', 'Roll', NULL),
  ('PC-KD-5', 'Tisue Roll Bamboo', 'Kebutuhan Dapur', 'Roll', NULL),
  ('PC-KD-6', 'Tissue Hand Towel', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-7', 'Tissue wajah', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-8', 'Loxus', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-9', 'Pengharum ruangan gantung', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-10', 'Pengharum ruangan semprot', 'Kebutuhan Dapur', 'Kaleng', NULL),
  ('PC-KD-11', 'Pengharum ruangan (Redd Diffuser)', 'Kebutuhan Dapur', 'Botol', NULL),
  ('PC-KD-12', 'Cling Pembersih Kaca 425ml', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-13', 'Prostex 1000ml', 'Kebutuhan Dapur', 'Botol', NULL),
  ('PC-KD-14', 'Sabun cuci piring', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-15', 'Karbol', 'Kebutuhan Dapur', 'Botol', NULL),
  ('PC-KD-16', 'Pembersih lantai (4L)', 'Kebutuhan Dapur', 'Botol', NULL),
  ('PC-KD-17', 'Sabun Colek', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-18', 'Detergent Bubuk', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-19', 'Hand Soap', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-20', 'Kif', 'Kebutuhan Dapur', 'Botol', NULL),
  ('PC-KD-21', 'Baygon Semprot', 'Kebutuhan Dapur', 'Kaleng', NULL),
  ('PC-KD-22', 'Obat nyamuk elektrik', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-23', 'Lem Tikus', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-24', 'Lem Lalat', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-25', 'Spons Cuci piring', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-26', 'Kawat cuci piring', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-27', 'Lap Dapur', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-28', 'Kamper isi 5', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-29', 'Plastik sampah Hitam 90x120', 'Kebutuhan Dapur', 'Pack', NULL),
  ('PC-KD-30', 'Plastik sampah HItam 60x100', 'Kebutuhan Dapur', 'Pack', NULL),
  ('PC-KD-31', 'Plastik sampah Merah/Putih besar', 'Kebutuhan Dapur', 'Pack', NULL),
  ('PC-KD-32', 'Plastik sampah kecil', 'Kebutuhan Dapur', 'Pack', NULL),
  ('PC-KD-33', 'Sapu Ijuk Nilon', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-34', 'Sapu Lidi', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-35', 'Pel', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-36', 'Pel (Refill biru)', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-37', 'Floor squegee', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-38', 'Window Squegee 35cm', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-39', 'Window Washer 35cm', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-40', 'Kemoceng', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-41', 'Ember', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-42', 'Pengki', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-43', 'Kanebo', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-44', 'Sikat Botol', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-45', 'Sikat Toilet', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-46', 'Sikat Lantai Panjang', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-47', 'Botol pump', 'Kebutuhan Dapur', 'Botol', NULL),
  ('PC-KD-48', 'Mesin Pengharum ruangan Matic', 'Kebutuhan Dapur', 'Set', NULL),
  ('PC-KD-49', 'Dispenser Tissue', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-50', 'Red Pad cleaner', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-KD-51', 'Sendok plastik', 'Kebutuhan Dapur', 'Pack', NULL),
  ('PC-KD-52', 'Gelas cup', 'Kebutuhan Dapur', 'Pack', NULL),
  ('PC-KD-53', 'Keset lantai', 'Kebutuhan Dapur', 'Pcs', NULL),
  ('PC-ATK-1', 'KERTAS HVS A4', 'ATK', 'Box', NULL),
  ('PC-ATK-2', 'PULPEN PILOT/ STANDARD HITAM', 'ATK', 'Lusin', NULL),
  ('PC-ATK-3', 'SPIDOL BIRU WHITE BOARD', 'ATK', 'Lusin', NULL),
  ('PC-ATK-4', 'SPIDOL HITAM WHITE BOARD', 'ATK', 'Lusin', NULL),
  ('PC-ATK-5', 'SPIDOL MERAH WHITE BOARD', 'ATK', 'Lusin', NULL),
  ('PC-ATK-6', 'PULPEN GEL BIRU', 'ATK', 'Lusin', NULL),
  ('PC-ATK-7', 'PULPEN GEL HITAM', 'ATK', 'Lusin', NULL),
  ('PC-ATK-8', 'PULPEN GEL MERAH', 'ATK', 'Lusin', NULL),
  ('PC-ATK-9', 'PULPEN SNOWMAN OHP OPF HITAM', 'ATK', 'Lusin', NULL),
  ('PC-ATK-10', 'SPIDOL PERMANENT HITAM', 'ATK', 'Lusin', NULL),
  ('PC-ATK-11', 'ORDNER / BANTEX MEDIUM', 'ATK', 'Lusin', NULL),
  ('PC-ATK-12', 'MAP TRANSPARANT', 'ATK', 'Lusin', NULL),
  ('PC-ATK-13', 'AMPLOP PUTIH PAPERLINE 110X230 mm', 'ATK', 'Box', NULL),
  ('PC-ATK-14', 'TINTA SPIDOL WHITEBOARD', 'ATK', 'Botol', NULL),
  ('PC-ATK-15', 'TINTA SPIDOL PERMANENT', 'ATK', 'Botol', NULL),
  ('PC-ATK-16', 'Stabilo', 'ATK', 'Pcs', NULL),
  ('PC-ATK-17', 'PENSIL MEKANIK (Joyko)', 'ATK', 'Pcs', NULL),
  ('PC-ATK-18', 'BUSINESS FILE', 'ATK', 'Lusin', NULL),
  ('PC-ATK-19', 'PENSIL 2B (Joyko/Fabercastle)', 'ATK', 'Pcs', NULL),
  ('PC-ATK-20', 'REFIL PENSIL MEKANIK (Joyko)', 'ATK', 'Pcs', NULL),
  ('PC-ATK-21', 'PAPER CLIP KECIL No 1', 'ATK', 'Pack', NULL),
  ('PC-ATK-22', 'GUNTING BESAR', 'ATK', 'Pcs', NULL),
  ('PC-ATK-23', 'PAPER CLIP BESAR No 5', 'ATK', 'Pack', NULL),
  ('PC-ATK-24', 'TINTA STEMPEL BIRU', 'ATK', 'Botol', NULL),
  ('PC-ATK-25', 'TINTA STEMPEL HITAM', 'ATK', 'Botol', NULL),
  ('PC-ATK-26', 'STEMPEL GMI KECIL', 'ATK', 'Pcs', NULL),
  ('PC-ATK-27', 'BANTALAN STEMPEL NO 1', 'ATK', 'Pcs', NULL),
  ('PC-ATK-28', 'ORDNER / BANTEK KECIL', 'ATK', 'Lusin', NULL),
  ('PC-ATK-29', 'refill isi pulpen biru', 'ATK', 'Lusin', NULL),
  ('PC-ATK-30', 'refill isi pulpen hitam', 'ATK', 'Lusin', NULL),
  ('PC-ATK-31', 'BINDER CLIP NO 107', 'ATK', 'Pack', NULL),
  ('PC-ATK-32', 'STEPLES NO 10', 'ATK', 'Pack', NULL),
  ('PC-ATK-33', 'KERTAS A4 DOTMATRIX 3PLY', 'ATK', 'Box', NULL),
  ('PC-ATK-34', 'KERTAS A4 DOTMATRIX 4PLY', 'ATK', 'Box', NULL),
  ('PC-ATK-35', 'PENGHAPUS (Joyko)', 'ATK', 'Pcs', NULL),
  ('PC-ATK-36', 'PAPER CLIP SEDANG No 3 (Joyko)', 'ATK', 'Pack', NULL),
  ('PC-ATK-37', 'BINDER CLIP NO 105', 'ATK', 'Pack', NULL),
  ('PC-ATK-38', 'LABEL TAPRE TOM&JERRY no 99', 'ATK', 'Lembar', NULL),
  ('PC-ATK-39', 'LABEL TAPRE TOM&JERRY no 125 atau 108', 'ATK', 'Lembar', NULL),
  ('PC-ATK-40', 'LABEL TAPRE TOM&JERRY No 103', 'ATK', 'Lembar', NULL),
  ('PC-ATK-41', 'BINDER CLIP NO 111', 'ATK', 'Pack', NULL),
  ('PC-ATK-42', 'BINDER CLIP NO 155', 'ATK', 'Pack', NULL),
  ('PC-ATK-43', 'POST IT PANJANG', 'ATK', 'Pcs', NULL),
  ('PC-ATK-44', 'POST IT Sign Here', 'ATK', 'Pcs', NULL),
  ('PC-ATK-45', 'DOUBEL TIP KECIL', 'ATK', 'Roll', NULL),
  ('PC-ATK-46', 'DOUBLE TAPE SEDANG', 'ATK', 'Roll', NULL),
  ('PC-ATK-47', 'DOUBLE TAPE FOAM', 'ATK', 'Roll', NULL),
  ('PC-ATK-48', 'BINDER CLIP NO 200 (Joyko)', 'ATK', 'Pack', NULL),
  ('PC-ATK-49', 'BINDER CLIP NO 260 (Joyko)', 'ATK', 'Pack', NULL),
  ('PC-ATK-50', 'TIPE EX CAIR', 'ATK', 'Pcs', NULL),
  ('PC-ATK-51', 'PAKU MADING TRUSCO PUSH', 'ATK', 'Pcs', NULL),
  ('PC-ATK-52', 'BINDER CLIP NO 280 (Joyko)', 'ATK', 'Pack', NULL),
  ('PC-ATK-53', 'ISI STEPLES STANDAR no 3', 'ATK', 'Pack', NULL),
  ('PC-ATK-54', 'POST IT KECIL (Joyko - MMS-0653)', 'ATK', 'Pcs', NULL),
  ('PC-ATK-55', 'POST IT SEDANG 75X75 (Joyko - MMS-3)', 'ATK', 'Pcs', NULL),
  ('PC-ATK-56', 'LAKBAN PLASTIK BENING BESAR', 'ATK', 'Roll', NULL),
  ('PC-ATK-57', 'LAKBAN PLASTIK BENING SEDANG', 'ATK', 'Roll', NULL),
  ('PC-ATK-58', 'LAKBAN COKLAT BESAR', 'ATK', 'Roll', NULL),
  ('PC-ATK-59', 'LAKBAN KERTAS KECIL', 'ATK', 'Roll', NULL),
  ('PC-ATK-60', 'LAKBAN KERTAS BESAR', 'ATK', 'Roll', NULL),
  ('PC-ATK-61', 'LAKBAN FRAGILE', 'ATK', 'Roll', NULL),
  ('PC-ATK-62', 'LAKBAN HITAM', 'ATK', 'Roll', NULL),
  ('PC-ATK-63', 'AMPLOP COKELAT', 'ATK', 'Box', NULL),
  ('PC-ATK-64', 'MAP COKLAT TALI', 'ATK', 'Pack', NULL),
  ('PC-ATK-65', 'MAP KANCING/SLETING TRANSPARANT', 'ATK', 'Pack', NULL),
  ('PC-ATK-66', 'ISI CUTTER BESAR', 'ATK', 'Set', NULL),
  ('PC-ATK-67', 'CUTTER BESAR', 'ATK', 'Pcs', NULL),
  ('PC-ATK-68', 'ISI CUTTER KECIL', 'ATK', 'Set', NULL),
  ('PC-ATK-69', 'CUTTER KECIL', 'ATK', 'Pcs', NULL),
  ('PC-ATK-70', 'PENGGARIS BESI 30CM', 'ATK', 'Pcs', NULL),
  ('PC-ATK-71', 'PENGGARIS PLASTIK 30CM', 'ATK', 'Pcs', NULL),
  ('PC-ATK-72', 'LEM KERTAS ROLL', 'ATK', 'Pcs', NULL),
  ('PC-ATK-73', 'CORRECTION TAPE (Joyko)', 'ATK', 'Pcs', NULL),
  ('PC-ATK-74', 'ISI STEPLES no 10 (Joyko)', 'ATK', 'Pack', NULL),
  ('PC-ATK-75', 'STEPLES NO 3', 'ATK', 'Pcs', NULL),
  ('PC-ATK-76', 'AMPLOP PUTIH PAPERLINE 92X165 mm', 'ATK', 'Box', NULL),
  ('PC-ATK-77', 'BINDEX FILE BOX', 'ATK', 'Pcs', NULL),
  ('PC-ATK-78', 'BATERY AA (Alkaline)', 'ATK', 'Set', NULL),
  ('PC-ATK-79', 'Sheet protector F4', 'ATK', 'Pack', NULL),
  ('PC-ATK-80', 'BATERY AAA (Alkaline)', 'ATK', 'Set', NULL),
  ('PC-ATK-81', 'Bantex Strong Line A4 divider Bulan', 'ATK', 'Pack', NULL),
  ('PC-ATK-82', 'Bantex Storng Line 6050-00 10 tab divider', 'ATK', 'Pack', NULL),
  ('PC-ATK-83', 'PEMBOLONG KERTAS', 'ATK', 'Set', NULL),
  ('PC-ATK-84', 'Buku Nota A5', 'ATK', 'Pcs', NULL),
  ('PC-ATK-85', 'GUNTING SEDANG', 'ATK', 'Pcs', NULL),
  ('PC-ATK-86', 'Map Gantung', 'ATK', 'Pcs', NULL),
  ('PC-ATK-87', 'Map Gantung Hijau', 'ATK', 'Pcs', NULL),
  ('PC-ATK-88', 'RAUTAN PENSIL BESAR', 'ATK', 'Pcs', NULL),
  ('PC-ATK-89', 'Clear holder isi 60', 'ATK', 'Pcs', NULL),
  ('PC-ATK-90', 'Clear holder isi 40', 'ATK', 'Pcs', NULL),
  ('PC-ATK-91', 'Clear holder isi 20', 'ATK', 'Pcs', NULL),
  ('PC-ATK-92', 'Papan jalan', 'ATK', 'Pcs', NULL),
  ('PC-ATK-93', 'Dispenser solasi', 'ATK', 'Pcs', NULL);
