-- Melengkapi Management Petty Cash (admin only) jadi kontrol PENUH A-Z atas
-- seluruh rantai dokumen (Pengajuan -> Voucher -> Sub-Voucher -> Deklarasi),
-- BUKAN cuma override status/approvals (sudah ada, lihat
-- petty-cash-admin-management-setup.sql). Tiga kemampuan baru, semua lewat
-- RPC SECURITY DEFINER (bukan RLS blanket) supaya konsistensi antar dokumen
-- SELALU dijaga otomatis oleh DB, bukan berharap client selalu benar:
--
--  1. HAPUS BERANTAI (`admin_delete_petty_cash_document`) - hapus Pengajuan
--     otomatis ikut menghapus Voucher -> Sub-Voucher -> Deklarasi
--     turunannya, DAN me-refund dana yang sudah ditarik sub-voucher kembali
--     ke `petty_cash_budget.current_budget` (simetris dgn potongannya di
--     create_petty_cash_sub_voucher). Kalau yang dihapus Deklarasi/Voucher
--     saja (bukan dari Pengajuan), status "Selesai" Voucher induk yang
--     sudah tercapai otomatis di-recheck & diturunkan lagi ke "Approved"
--     kalau syaratnya sudah tidak terpenuhi lagi (lihat
--     _pc_admin_recheck_voucher_completion - kebalikan dari trigger
--     handle_petty_cash_deklarasi_complete_voucher,
--     petty-cash-voucher-deklarasi-complete-setup.sql).
--
--  2. GANTI KODE BERANTAI (`admin_rename_petty_cash_kode`) - kalau yang
--     diganti kode_voucher, SEMUA kode_sub_voucher turunannya (format
--     "{kode_voucher}-SV{urutan}") otomatis ikut diganti prefix-nya supaya
--     tetap konsisten (bukan nyisa kode lama yang membingungkan). Dokumen
--     lain (Pengajuan/Deklarasi) tidak perlu ikut berubah karena relasinya
--     ke Voucher/Sub-Voucher SELALU lewat foreign key id (pengajuan_id/
--     voucher_id/sub_voucher_id) - label "kode_pengajuan"/"kode_voucher"
--     yang ditampilkan di dokumen turunan itu SELALU live-join, bukan
--     disalin literal, jadi otomatis ikut ter-update tanpa perlu disentuh.
--
--  3. EDIT PAKSA (`admin_force_update_pengajuan/voucher/deklarasi/
--     sub_voucher`) - admin bisa mengedit item/tanggal/departemen/company/
--     budget/catatan/lampiran dokumen APA PUN, di status APA PUN (beda dari
--     "Edit & Setujui" approver yang cuma bisa dipakai approver yang
--     gilirannya sedang pending). total_amount SELALU dihitung ULANG dari
--     items yang dikirim (bukan dipercaya dari client) - konsistensi harga
--     x qty x total tetap terjaga. Khusus Sub-Voucher: qty/harga BOLEH
--     disesuaikan (item_index & barisnya TIDAK BOLEH ditambah/dihapus -
--     lihat komentar di fungsinya, supaya "sisa qty yang belum ditarik" di
--     create_petty_cash_sub_voucher tetap valid) dan SELISIH nominalnya
--     otomatis disesuaikan ke `petty_cash_budget.current_budget` (bukan
--     dibiarkan nyimpang dari budget yang sudah kepotong).
--
-- Setiap aksi WAJIB menyertakan alasan (`p_reason`) dan tercatat permanen di
-- tabel audit baru `petty_cash_admin_audit_log` (select admin-only, TIDAK
-- ADA policy insert/update/delete - satu-satunya jalan masuk baris baru
-- adalah dari dalam RPC di bawah, supaya log ini genuine/tidak bisa
-- dipalsukan lewat client).
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama), SETELAH semua
-- file petty-cash-*-setup.sql lain (termasuk
-- petty-cash-sub-voucher-payment-setup.sql).

-- ============================================================
-- 0. Tabel audit log
-- ============================================================

create table if not exists public.petty_cash_admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id) on delete set null,
  action text not null, -- 'delete' | 'rename_kode' | 'force_edit'
  doc_type text not null, -- 'pengajuan' | 'voucher' | 'sub_voucher' | 'deklarasi'
  doc_id bigint not null,
  kode text,
  reason text not null,
  detail jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists idx_petty_cash_admin_audit_log_doc
  on public.petty_cash_admin_audit_log (doc_type, doc_id);
create index if not exists idx_petty_cash_admin_audit_log_created_at
  on public.petty_cash_admin_audit_log (created_at desc);

alter table public.petty_cash_admin_audit_log enable row level security;

drop policy if exists "petty_cash_admin_audit_log_select" on public.petty_cash_admin_audit_log;
create policy "petty_cash_admin_audit_log_select"
  on public.petty_cash_admin_audit_log
  for select
  to authenticated
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- SENGAJA TIDAK ADA policy insert/update/delete - satu-satunya jalan masuk
-- baris baru adalah dari dalam RPC admin_* di bawah (SECURITY DEFINER,
-- bypass RLS), supaya log ini tidak bisa ditulis/diubah/dihapus manual
-- lewat client (menjaga integritasnya sebagai jejak audit genuine).

-- ============================================================
-- 1. Helper internal (TIDAK dipanggil langsung dari client - lihat revoke
--    execute di akhir tiap fungsi. Semua pengecekan role admin ada di
--    fungsi PEMANGGIL/entry-point, bukan di sini).
-- ============================================================

-- Kebalikan dari trigger handle_petty_cash_deklarasi_complete_voucher
-- (petty-cash-voucher-deklarasi-complete-setup.sql): dipanggil setelah
-- sebuah Deklarasi/Sub-Voucher DIHAPUS - kalau Voucher induknya SUDAH
-- "Selesai" tapi syaratnya (semua sub-voucher sudah tuntas dideklarasikan
-- approved DAN totalnya menutup total_amount) sekarang TIDAK terpenuhi lagi
-- (karena salah satu Deklarasi/Sub-Voucher yang jadi syaratnya baru saja
-- dihapus admin), turunkan lagi ke "Approved" - supaya status Voucher selalu
-- mencerminkan kondisi riil, bukan status basi dari sebelum dihapus.
create or replace function public._pc_admin_recheck_voucher_completion(
  p_voucher_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
  v_total_amount numeric;
  v_total_drawn numeric;
  v_all_reconciled boolean;
begin
  select status, total_amount into v_status, v_total_amount
  from public.petty_cash_voucher where id = p_voucher_id;

  if v_status is null then
    return; -- Voucher-nya sendiri sudah ikut terhapus (cascade dari atasnya).
  end if;

  if v_status <> 'Selesai' then
    return; -- Cuma relevan kalau sedang "Selesai" - status lain tidak disentuh.
  end if;

  select coalesce(sum(amount), 0) into v_total_drawn
  from public.petty_cash_sub_voucher where voucher_id = p_voucher_id;

  select not exists (
    select 1 from public.petty_cash_sub_voucher sv
    where sv.voucher_id = p_voucher_id
      and not exists (
        select 1 from public.petty_cash_deklarasi d
        where d.sub_voucher_id = sv.id and d.status = 'Approved'
      )
  ) into v_all_reconciled;

  if not (v_total_drawn >= v_total_amount and v_all_reconciled) then
    update public.petty_cash_voucher
    set status = 'Approved', updated_at = now()
    where id = p_voucher_id and status = 'Selesai';
  end if;
end;
$$;

revoke execute on function public._pc_admin_recheck_voucher_completion(bigint) from public;

-- Hapus SATU Sub-Voucher (+ Deklarasi turunannya kalau ada) & refund
-- nominalnya kembali ke Budget - simetris persis dgn potongan budget saat
-- create_petty_cash_sub_voucher, arah sebaliknya. Dipakai baik utk hapus
-- Sub-Voucher langsung MAUPUN sebagai bagian dari cascade hapus Voucher.
create or replace function public._pc_admin_refund_sub_voucher(
  p_sub_voucher_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sv public.petty_cash_sub_voucher%rowtype;
  v_voucher public.petty_cash_voucher%rowtype;
  v_deklarasi_id bigint;
  v_deklarasi_kode text;
  v_new_budget numeric;
begin
  select * into v_sv from public.petty_cash_sub_voucher where id = p_sub_voucher_id for update;
  if not found then
    raise exception 'Sub-Voucher tidak ditemukan.';
  end if;

  select * into v_voucher from public.petty_cash_voucher where id = v_sv.voucher_id for update;

  -- Deklarasi turunannya (unique sub_voucher_id, paling banyak 1 baris) -
  -- hapus dulu supaya FK petty_cash_deklarasi.sub_voucher_id (on delete
  -- restrict) tidak menghalangi hapus Sub-Voucher-nya sendiri di bawah.
  select id, kode_deklarasi into v_deklarasi_id, v_deklarasi_kode
  from public.petty_cash_deklarasi where sub_voucher_id = p_sub_voucher_id;

  if v_deklarasi_id is not null then
    delete from public.petty_cash_deklarasi where id = v_deklarasi_id;
  end if;

  if v_voucher.budget_id is not null then
    update public.petty_cash_budget
    set current_budget = current_budget + v_sv.amount
    where id = v_voucher.budget_id
    returning current_budget into v_new_budget;

    insert into public.petty_cash_budget_history (
      budget_id, ref_type, ref_id, user_id, change_amount, previous_budget, new_budget, description
    ) values (
      v_voucher.budget_id, 'refund', v_sv.id, auth.uid(), v_sv.amount,
      v_new_budget - v_sv.amount, v_new_budget,
      'Refund penghapusan Sub-Voucher ' || v_sv.kode_sub_voucher || ' oleh admin - alasan: ' || p_reason
    );
  end if;

  delete from public.petty_cash_sub_voucher where id = p_sub_voucher_id;

  perform public._pc_admin_recheck_voucher_completion(v_sv.voucher_id);

  return jsonb_build_object(
    'sub_voucher_id', v_sv.id,
    'sub_voucher_kode', v_sv.kode_sub_voucher,
    'refunded_amount', v_sv.amount,
    'deklarasi_id', v_deklarasi_id,
    'deklarasi_kode', v_deklarasi_kode
  );
end;
$$;

revoke execute on function public._pc_admin_refund_sub_voucher(bigint, text) from public;

-- Hapus SATU Voucher berikut SELURUH Sub-Voucher (& Deklarasi turunannya
-- masing-masing, + refund budget) - dipakai baik utk hapus Voucher langsung
-- MAUPUN sebagai bagian dari cascade hapus Pengajuan.
create or replace function public._pc_admin_delete_voucher_cascade(
  p_voucher_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_voucher public.petty_cash_voucher%rowtype;
  v_sv record;
  v_refunds jsonb := '[]'::jsonb;
  v_total_refunded numeric := 0;
  v_refund_result jsonb;
begin
  select * into v_voucher from public.petty_cash_voucher where id = p_voucher_id for update;
  if not found then
    raise exception 'Voucher tidak ditemukan.';
  end if;

  for v_sv in
    select id from public.petty_cash_sub_voucher where voucher_id = p_voucher_id
  loop
    v_refund_result := public._pc_admin_refund_sub_voucher(v_sv.id, p_reason);
    v_refunds := v_refunds || jsonb_build_array(v_refund_result);
    v_total_refunded := v_total_refunded + coalesce((v_refund_result->>'refunded_amount')::numeric, 0);
  end loop;

  delete from public.petty_cash_voucher where id = p_voucher_id;

  return jsonb_build_object(
    'voucher_id', v_voucher.id,
    'voucher_kode', v_voucher.kode_voucher,
    'sub_vouchers_deleted', v_refunds,
    'total_refunded', v_total_refunded
  );
end;
$$;

revoke execute on function public._pc_admin_delete_voucher_cascade(bigint, text) from public;

-- ============================================================
-- 2. HAPUS BERANTAI - entry point (admin only, dipanggil client)
-- ============================================================

create or replace function public.admin_delete_petty_cash_document(
  p_doc_type text,
  p_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_summary jsonb;
  v_kode text;
  v_pengajuan public.petty_cash_pengajuan%rowtype;
  v_voucher_id bigint;
  v_deklarasi public.petty_cash_deklarasi%rowtype;
begin
  select role into v_role from public.profiles where id = auth.uid();
  if v_role is distinct from 'admin' then
    raise exception 'Hanya admin yang boleh menghapus dokumen Petty Cash.';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'Alasan penghapusan wajib diisi.';
  end if;

  if p_doc_type = 'deklarasi' then
    select * into v_deklarasi from public.petty_cash_deklarasi where id = p_id for update;
    if not found then
      raise exception 'Deklarasi tidak ditemukan.';
    end if;

    delete from public.petty_cash_deklarasi where id = p_id;
    perform public._pc_admin_recheck_voucher_completion(v_deklarasi.voucher_id);

    v_kode := v_deklarasi.kode_deklarasi;
    v_summary := jsonb_build_object(
      'deklarasi_id', v_deklarasi.id,
      'deklarasi_kode', v_deklarasi.kode_deklarasi
    );

  elsif p_doc_type = 'sub_voucher' then
    v_summary := public._pc_admin_refund_sub_voucher(p_id, p_reason);
    v_kode := v_summary->>'sub_voucher_kode';

  elsif p_doc_type = 'voucher' then
    v_summary := public._pc_admin_delete_voucher_cascade(p_id, p_reason);
    v_kode := v_summary->>'voucher_kode';

  elsif p_doc_type = 'pengajuan' then
    select * into v_pengajuan from public.petty_cash_pengajuan where id = p_id for update;
    if not found then
      raise exception 'Pengajuan tidak ditemukan.';
    end if;

    select id into v_voucher_id from public.petty_cash_voucher where pengajuan_id = p_id;

    if v_voucher_id is not null then
      v_summary := public._pc_admin_delete_voucher_cascade(v_voucher_id, p_reason);
    else
      v_summary := '{}'::jsonb;
    end if;

    delete from public.petty_cash_pengajuan where id = p_id;

    v_kode := v_pengajuan.kode_pengajuan;
    v_summary := v_summary || jsonb_build_object(
      'pengajuan_id', v_pengajuan.id,
      'pengajuan_kode', v_pengajuan.kode_pengajuan
    );

  else
    raise exception 'Tipe dokumen tidak dikenal: %', p_doc_type;
  end if;

  insert into public.petty_cash_admin_audit_log (
    admin_id, action, doc_type, doc_id, kode, reason, detail
  ) values (
    auth.uid(), 'delete', p_doc_type, p_id, v_kode, p_reason, v_summary
  );

  return v_summary;
end;
$$;

grant execute on function public.admin_delete_petty_cash_document(text, bigint, text) to authenticated;

-- ============================================================
-- 3. GANTI KODE BERANTAI
-- ============================================================

create or replace function public.admin_rename_petty_cash_kode(
  p_doc_type text,
  p_id bigint,
  p_new_kode text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_old_kode text;
  v_new_kode text := trim(p_new_kode);
  v_cascaded_count int := 0;
begin
  select role into v_role from public.profiles where id = auth.uid();
  if v_role is distinct from 'admin' then
    raise exception 'Hanya admin yang boleh mengubah kode dokumen Petty Cash.';
  end if;
  if v_new_kode = '' then
    raise exception 'Kode baru tidak boleh kosong.';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'Alasan perubahan kode wajib diisi.';
  end if;

  if p_doc_type = 'pengajuan' then
    select kode_pengajuan into v_old_kode from public.petty_cash_pengajuan where id = p_id for update;
    if not found then raise exception 'Pengajuan tidak ditemukan.'; end if;
    update public.petty_cash_pengajuan set kode_pengajuan = v_new_kode, updated_at = now() where id = p_id;

  elsif p_doc_type = 'voucher' then
    select kode_voucher into v_old_kode from public.petty_cash_voucher where id = p_id for update;
    if not found then raise exception 'Voucher tidak ditemukan.'; end if;
    update public.petty_cash_voucher set kode_voucher = v_new_kode, updated_at = now() where id = p_id;

    -- Cascade: kode_sub_voucher = "{kode_voucher}-SV{urutan}" - ganti
    -- prefix lama dgn yang baru, suffix "-SV{n}" dipertahankan apa adanya.
    -- Pakai left()/substring() posisional (bukan LIKE) supaya aman dari
    -- karakter wildcard SQL (%, _) andai kode mengandungnya.
    update public.petty_cash_sub_voucher
    set kode_sub_voucher = v_new_kode || substring(kode_sub_voucher from length(v_old_kode) + 1),
        updated_at = now()
    where voucher_id = p_id
      and left(kode_sub_voucher, length(v_old_kode) + 1) = v_old_kode || '-';
    get diagnostics v_cascaded_count = row_count;

  elsif p_doc_type = 'sub_voucher' then
    select kode_sub_voucher into v_old_kode from public.petty_cash_sub_voucher where id = p_id for update;
    if not found then raise exception 'Sub-Voucher tidak ditemukan.'; end if;
    update public.petty_cash_sub_voucher set kode_sub_voucher = v_new_kode, updated_at = now() where id = p_id;

  elsif p_doc_type = 'deklarasi' then
    select kode_deklarasi into v_old_kode from public.petty_cash_deklarasi where id = p_id for update;
    if not found then raise exception 'Deklarasi tidak ditemukan.'; end if;
    update public.petty_cash_deklarasi set kode_deklarasi = v_new_kode, updated_at = now() where id = p_id;

  else
    raise exception 'Tipe dokumen tidak dikenal: %', p_doc_type;
  end if;

  insert into public.petty_cash_admin_audit_log (
    admin_id, action, doc_type, doc_id, kode, reason, detail
  ) values (
    auth.uid(), 'rename_kode', p_doc_type, p_id, v_new_kode, p_reason,
    jsonb_build_object(
      'kode_lama', v_old_kode, 'kode_baru', v_new_kode,
      'cascaded_sub_voucher_count', v_cascaded_count
    )
  );

  return jsonb_build_object(
    'kode_lama', v_old_kode,
    'kode_baru', v_new_kode,
    'cascaded_sub_voucher_count', v_cascaded_count
  );
exception
  when unique_violation then
    raise exception 'Kode "%" sudah dipakai dokumen lain. Gunakan kode yang berbeda.', v_new_kode;
end;
$$;

grant execute on function public.admin_rename_petty_cash_kode(text, bigint, text, text) to authenticated;

-- ============================================================
-- 4. EDIT PAKSA (admin only, tanpa syarat giliran approval / status)
-- ============================================================

create or replace function public.admin_force_update_pengajuan(
  p_id bigint,
  p_needed_date date,
  p_week_of_month int,
  p_site text,
  p_company_code text,
  p_department text,
  p_budget_id bigint,
  p_notes text,
  p_items jsonb,
  p_attachments jsonb,
  p_reason text
)
returns public.petty_cash_pengajuan
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_row public.petty_cash_pengajuan%rowtype;
  v_total numeric;
begin
  select role into v_role from public.profiles where id = auth.uid();
  if v_role is distinct from 'admin' then
    raise exception 'Hanya admin yang boleh melakukan edit paksa dokumen Petty Cash.';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'Alasan edit paksa wajib diisi.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Minimal harus ada 1 barang.';
  end if;

  select coalesce(sum((elem->>'subtotal')::numeric), 0) into v_total
  from jsonb_array_elements(p_items) elem;

  update public.petty_cash_pengajuan
  set needed_date = p_needed_date,
      week_of_month = p_week_of_month,
      site = p_site,
      company_code = p_company_code,
      department = p_department,
      budget_id = p_budget_id,
      notes = p_notes,
      items = p_items,
      attachments = coalesce(p_attachments, '[]'::jsonb),
      total_amount = v_total,
      updated_at = now()
  where id = p_id
  returning * into v_row;

  if v_row.id is null then
    raise exception 'Pengajuan tidak ditemukan.';
  end if;

  insert into public.petty_cash_admin_audit_log (
    admin_id, action, doc_type, doc_id, kode, reason, detail
  ) values (
    auth.uid(), 'force_edit', 'pengajuan', p_id, v_row.kode_pengajuan, p_reason,
    jsonb_build_object('total_amount_baru', v_total)
  );

  return v_row;
end;
$$;

grant execute on function public.admin_force_update_pengajuan(
  bigint, date, int, text, text, text, bigint, text, jsonb, jsonb, text
) to authenticated;

create or replace function public.admin_force_update_voucher(
  p_id bigint,
  p_needed_date date,
  p_week_of_month int,
  p_site text,
  p_company_code text,
  p_department text,
  p_budget_id bigint,
  p_notes text,
  p_items jsonb,
  p_attachments jsonb,
  p_reason text
)
returns public.petty_cash_voucher
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_row public.petty_cash_voucher%rowtype;
  v_total numeric;
begin
  select role into v_role from public.profiles where id = auth.uid();
  if v_role is distinct from 'admin' then
    raise exception 'Hanya admin yang boleh melakukan edit paksa dokumen Petty Cash.';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'Alasan edit paksa wajib diisi.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Minimal harus ada 1 barang.';
  end if;

  select coalesce(sum((elem->>'subtotal')::numeric), 0) into v_total
  from jsonb_array_elements(p_items) elem;

  update public.petty_cash_voucher
  set needed_date = p_needed_date,
      week_of_month = p_week_of_month,
      site = p_site,
      company_code = p_company_code,
      department = p_department,
      budget_id = p_budget_id,
      notes = p_notes,
      items = p_items,
      attachments = coalesce(p_attachments, '[]'::jsonb),
      total_amount = v_total,
      updated_at = now()
  where id = p_id
  returning * into v_row;

  if v_row.id is null then
    raise exception 'Voucher tidak ditemukan.';
  end if;

  insert into public.petty_cash_admin_audit_log (
    admin_id, action, doc_type, doc_id, kode, reason, detail
  ) values (
    auth.uid(), 'force_edit', 'voucher', p_id, v_row.kode_voucher, p_reason,
    jsonb_build_object('total_amount_baru', v_total)
  );

  return v_row;
end;
$$;

grant execute on function public.admin_force_update_voucher(
  bigint, date, int, text, text, text, bigint, text, jsonb, jsonb, text
) to authenticated;

-- Deklarasi TIDAK punya needed_date/week_of_month/budget_id sendiri (lihat
-- komentar PettyCashDeklarasi, type/index.ts) - week_of_month/site tetap
-- ikut nilai yang disalin dari Voucher asalnya, sengaja TIDAK diedit lewat
-- sini juga (konsisten dgn EditDeklarasiEdits, services/pettyCashDeklarasiService.ts,
-- yang juga tidak mengekspos field itu ke approver).
create or replace function public.admin_force_update_deklarasi(
  p_id bigint,
  p_company_code text,
  p_department text,
  p_notes text,
  p_items jsonb,
  p_attachments jsonb,
  p_reason text
)
returns public.petty_cash_deklarasi
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_row public.petty_cash_deklarasi%rowtype;
  v_total numeric;
begin
  select role into v_role from public.profiles where id = auth.uid();
  if v_role is distinct from 'admin' then
    raise exception 'Hanya admin yang boleh melakukan edit paksa dokumen Petty Cash.';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'Alasan edit paksa wajib diisi.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Minimal harus ada 1 barang.';
  end if;

  select coalesce(sum((elem->>'subtotal')::numeric), 0) into v_total
  from jsonb_array_elements(p_items) elem;

  update public.petty_cash_deklarasi
  set company_code = p_company_code,
      department = p_department,
      notes = p_notes,
      items = p_items,
      attachments = coalesce(p_attachments, '[]'::jsonb),
      total_amount = v_total,
      updated_at = now()
  where id = p_id
  returning * into v_row;

  if v_row.id is null then
    raise exception 'Deklarasi tidak ditemukan.';
  end if;

  insert into public.petty_cash_admin_audit_log (
    admin_id, action, doc_type, doc_id, kode, reason, detail
  ) values (
    auth.uid(), 'force_edit', 'deklarasi', p_id, v_row.kode_deklarasi, p_reason,
    jsonb_build_object('total_amount_baru', v_total)
  );

  return v_row;
end;
$$;

grant execute on function public.admin_force_update_deklarasi(
  bigint, text, text, text, jsonb, jsonb, text
) to authenticated;

-- Sub-Voucher: BEDA dari 3 lainnya - `p_items` WAJIB punya persis set
-- `item_index` yang sama dgn baris yang sudah ada (tidak boleh
-- tambah/hapus/acak baris), cuma qty/unit_price/note per baris yang boleh
-- disesuaikan admin. Ini supaya "sisa qty yang belum ditarik" yang dihitung
-- create_petty_cash_sub_voucher (dari petty_cash_voucher.items dikurangi
-- SEMUA sub-voucher yang match item_index yang sama) tetap valid - kalau
-- item_index bebas diubah, perhitungan itu bisa jadi salah/hitungan ganda.
-- SELISIH nominal (amount baru - lama) otomatis disesuaikan ke
-- petty_cash_budget.current_budget Voucher induknya - supaya budget yang
-- sudah kepotong saat tarikan tetap match dgn nominal final Sub-Voucher ini
-- (naik = potong lagi selisihnya, gagal kalau sisa budget tidak cukup;
-- turun = refund selisihnya).
create or replace function public.admin_force_update_sub_voucher(
  p_id bigint,
  p_items jsonb,
  p_notes text,
  p_status text,
  p_payment_proof jsonb,
  p_reason text
)
returns public.petty_cash_sub_voucher
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_old public.petty_cash_sub_voucher%rowtype;
  v_row public.petty_cash_sub_voucher%rowtype;
  v_voucher public.petty_cash_voucher%rowtype;
  v_new_amount numeric;
  v_delta numeric;
  v_new_budget numeric;
  v_old_indexes int[];
  v_new_indexes int[];
begin
  select role into v_role from public.profiles where id = auth.uid();
  if v_role is distinct from 'admin' then
    raise exception 'Hanya admin yang boleh melakukan edit paksa Sub-Voucher.';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'Alasan edit paksa wajib diisi.';
  end if;
  if p_status not in ('Menunggu Pembayaran', 'Selesai') then
    raise exception 'Status tidak valid: %', p_status;
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Minimal harus ada 1 barang.';
  end if;

  select * into v_old from public.petty_cash_sub_voucher where id = p_id for update;
  if not found then
    raise exception 'Sub-Voucher tidak ditemukan.';
  end if;

  select array_agg((elem->>'item_index')::int order by (elem->>'item_index')::int)
  into v_old_indexes from jsonb_array_elements(v_old.items) elem;
  select array_agg((elem->>'item_index')::int order by (elem->>'item_index')::int)
  into v_new_indexes from jsonb_array_elements(p_items) elem;

  if v_new_indexes is distinct from v_old_indexes then
    raise exception 'Baris barang tidak boleh ditambah/dihapus - admin cuma bisa menyesuaikan qty/harga baris yang sudah ada.';
  end if;

  select coalesce(sum(((elem->>'qty')::numeric) * ((elem->>'unit_price')::numeric)), 0)
  into v_new_amount
  from jsonb_array_elements(p_items) elem;

  v_delta := v_new_amount - v_old.amount;

  select * into v_voucher from public.petty_cash_voucher where id = v_old.voucher_id for update;

  if v_delta <> 0 and v_voucher.budget_id is not null then
    update public.petty_cash_budget
    set current_budget = current_budget - v_delta
    where id = v_voucher.budget_id
      and (v_delta <= 0 or current_budget >= v_delta)
    returning current_budget into v_new_budget;

    if v_new_budget is null then
      raise exception 'Sisa budget departemen tidak mencukupi untuk kenaikan nominal ini.';
    end if;

    insert into public.petty_cash_budget_history (
      budget_id, ref_type, ref_id, user_id, change_amount, previous_budget, new_budget, description
    ) values (
      v_voucher.budget_id, 'adjustment', v_old.id, auth.uid(), -v_delta,
      v_new_budget + v_delta, v_new_budget,
      'Edit paksa admin Sub-Voucher ' || v_old.kode_sub_voucher || ' - alasan: ' || p_reason
    );
  end if;

  update public.petty_cash_sub_voucher
  set items = p_items,
      amount = v_new_amount,
      notes = p_notes,
      status = p_status,
      payment_proof = coalesce(p_payment_proof, payment_proof),
      updated_at = now()
  where id = p_id
  returning * into v_row;

  perform public._pc_admin_recheck_voucher_completion(v_old.voucher_id);

  insert into public.petty_cash_admin_audit_log (
    admin_id, action, doc_type, doc_id, kode, reason, detail
  ) values (
    auth.uid(), 'force_edit', 'sub_voucher', p_id, v_row.kode_sub_voucher, p_reason,
    jsonb_build_object(
      'amount_lama', v_old.amount, 'amount_baru', v_new_amount, 'status_baru', p_status
    )
  );

  return v_row;
end;
$$;

grant execute on function public.admin_force_update_sub_voucher(
  bigint, jsonb, text, text, jsonb, text
) to authenticated;
