-- "Template MR" - tabel `mr_templates`, daftar barang siap pakai untuk MR
-- rutin (mis. "ATK Bulanan", "Konsumsi Rapat") yang DISEDIAKAN GA - beda dari
-- petty_cash_pengajuan_template yang per-user, template di sini katalog
-- BERSAMA: dikelola GA (level approver) / admin, dibaca semua user login.
-- Requester tinggal pilih template di halaman Buat MR, barang-barangnya
-- otomatis dimuat, sisanya (qty, remarks, lampiran, dst) tetap bisa diedit
-- manual. Lihat app/(With Sidebar)/mr-template/MrTemplateClient.tsx (kelola)
-- & app/(With Sidebar)/material-request/buat/page.tsx (terapkan, juga lewat
-- ?template=<id>).
--
-- `orders` menyimpan snapshot Order (name, part_number, uom, qty,
-- estimasi_harga, note, barang_id) - estimasi_harga di-refresh ulang dari
-- barang.last_purchase_price saat template diterapkan (lihat
-- applyMrTemplate di services/mrTemplateService.ts), jadi harga di sini cuma
-- fallback kalau barang belum punya harga pembelian terakhir.
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama).

create table if not exists public.mr_templates (
  id bigint generated by default as identity primary key,
  nama_template text not null,
  deskripsi text,
  kategori text,
  remarks text,
  orders jsonb not null default '[]',
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_mr_templates_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.updated_at := now();
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists on_mr_templates_write on public.mr_templates;
create trigger on_mr_templates_write
  before insert or update on public.mr_templates
  for each row execute function public.handle_mr_templates_audit();

alter table public.mr_templates enable row level security;

-- Baca: semua user login (requester butuh lihat & pakai template).
drop policy if exists "mr_templates_select" on public.mr_templates;
create policy "mr_templates_select"
  on public.mr_templates
  for select
  to authenticated
  using (true);

-- Tulis (insert/update/delete): admin ATAU departemen setara GA dengan role
-- approver. Daftar departemen di bawah HARUS disamakan manual dengan
-- GA_DEPARTMENTS di lib/constants/departments.ts kalau nanti berubah - SQL
-- tidak bisa import konstanta TypeScript.
drop policy if exists "mr_templates_insert" on public.mr_templates;
create policy "mr_templates_insert"
  on public.mr_templates
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (
          p.role = 'admin'
          or (p.role = 'approver' and p.department in ('General Affair', 'HRGA-HSE'))
        )
    )
  );

drop policy if exists "mr_templates_update" on public.mr_templates;
create policy "mr_templates_update"
  on public.mr_templates
  for update
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (
          p.role = 'admin'
          or (p.role = 'approver' and p.department in ('General Affair', 'HRGA-HSE'))
        )
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (
          p.role = 'admin'
          or (p.role = 'approver' and p.department in ('General Affair', 'HRGA-HSE'))
        )
    )
  );

drop policy if exists "mr_templates_delete" on public.mr_templates;
create policy "mr_templates_delete"
  on public.mr_templates
  for delete
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and (
          p.role = 'admin'
          or (p.role = 'approver' and p.department in ('General Affair', 'HRGA-HSE'))
        )
    )
  );
