-- Fitur "Update Web" - changelog/pengumuman aplikasi internal. Admin upload
-- postingan (versi semantic x.y.z, judul, ringkasan singkat, detail rich
-- content Tiptap dgn gambar/video/link), semua user login bisa lihat daftar +
-- detail, komentar (pola `discussions` jsonb + RPC, sama seperti MR/PO/Petty
-- Cash), dan kasih reaction multi-emoji (fitur baru, tabel terpisah karena
-- butuh uniqueness per user+emoji, bukan pola jsonb).
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama). Butuh
-- `public.handle_updated_at()` (trigger generic, sudah ada dari schema awal,
-- lihat supabase/migrations/20260101000000_prod_schema.sql baris ~404).

-- ============================================================
-- 1. Tabel update_web_posts
-- ============================================================

create table if not exists public.update_web_posts (
  id bigint generated by default as identity primary key,
  version_major int not null,
  version_minor int not null,
  version_patch int not null,
  -- Kolom generated supaya "1.4.2" SELALU konsisten dgn 3 kolom int-nya -
  -- tidak mungkin nyimpang (tidak ada 2 sumber kebenaran yang bisa beda).
  version text generated always as (
    version_major::text || '.' || version_minor::text || '.' || version_patch::text
  ) stored,
  title text not null,
  thumbnail_url text,
  -- Ringkasan singkat (bullet list), array of string - ditampilkan di
  -- card list & bagian atas modal detail, terpisah dari `content` (body rich
  -- text lengkap).
  highlights jsonb not null default '[]',
  -- Tiptap JSON doc (body detail, support heading/gambar/video/link - lihat
  -- components/tiptap/update-post-editor.tsx).
  content jsonb not null default '{}',
  -- Komentar - pola SAMA PERSIS dgn petty_cash_pengajuan/voucher/deklarasi
  -- (kolom jsonb append-only, diisi lewat RPC di bawah, dirender pakai
  -- components/discussion-panel.tsx tanpa modifikasi).
  discussions jsonb not null default '[]',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (version_major, version_minor, version_patch)
);

create index if not exists idx_update_web_posts_created_at
  on public.update_web_posts (created_at desc);

drop trigger if exists on_update_web_posts_updated on public.update_web_posts;
create trigger on_update_web_posts_updated
  before update on public.update_web_posts
  for each row execute function public.handle_updated_at();

alter table public.update_web_posts enable row level security;

drop policy if exists "update_web_posts_select" on public.update_web_posts;
create policy "update_web_posts_select"
  on public.update_web_posts
  for select
  to authenticated
  using (true);

drop policy if exists "update_web_posts_insert_admin" on public.update_web_posts;
create policy "update_web_posts_insert_admin"
  on public.update_web_posts
  for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

drop policy if exists "update_web_posts_update_admin" on public.update_web_posts;
create policy "update_web_posts_update_admin"
  on public.update_web_posts
  for update
  to authenticated
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

drop policy if exists "update_web_posts_delete_admin" on public.update_web_posts;
create policy "update_web_posts_delete_admin"
  on public.update_web_posts
  for delete
  to authenticated
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- ============================================================
-- 2. Tabel update_web_post_reactions (multi-emoji, toggle per user+emoji)
-- ============================================================

create table if not exists public.update_web_post_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.update_web_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null check (emoji in ('👍', '❤️', '🎉', '😂', '😮', '🙏')),
  created_at timestamptz not null default now(),
  unique (post_id, user_id, emoji)
);

create index if not exists idx_update_web_post_reactions_post
  on public.update_web_post_reactions (post_id);

alter table public.update_web_post_reactions enable row level security;

drop policy if exists "update_web_post_reactions_select" on public.update_web_post_reactions;
create policy "update_web_post_reactions_select"
  on public.update_web_post_reactions
  for select
  to authenticated
  using (true);

-- Insert/delete TIDAK perlu RPC - user_id dikunci ke auth.uid() lewat
-- with check/using, jadi user cuma bisa nambah/hapus reaction miliknya
-- sendiri (toggle on/off), tidak bisa mengatasnamakan user lain.
drop policy if exists "update_web_post_reactions_insert_own" on public.update_web_post_reactions;
create policy "update_web_post_reactions_insert_own"
  on public.update_web_post_reactions
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "update_web_post_reactions_delete_own" on public.update_web_post_reactions;
create policy "update_web_post_reactions_delete_own"
  on public.update_web_post_reactions
  for delete
  to authenticated
  using (user_id = auth.uid());

-- ============================================================
-- 3. RPC: create_update_web_post (admin only, hitung versi ATOMIC)
-- ============================================================
--
-- p_version = null -> auto-increment PATCH dari versi tertinggi yang ada
-- (default 1.0.0 kalau belum ada postingan sama sekali). `for update` mengunci
-- baris versi tertinggi selama transaksi supaya 2 admin yang bikin post
-- bersamaan tidak dapat nomor PATCH yang sama (race condition).
-- p_version diisi "x.y.z" -> override manual, tetap divalidasi formatnya di
-- server (jangan percaya client), uniqueness dijaga otomatis oleh constraint
-- unique(version_major, version_minor, version_patch).

create or replace function public.create_update_web_post(
  p_title text,
  p_thumbnail_url text,
  p_highlights jsonb,
  p_content jsonb,
  p_version text default null
)
returns public.update_web_posts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_major int;
  v_minor int;
  v_patch int;
  v_row public.update_web_posts%rowtype;
begin
  select role into v_role from public.profiles where id = auth.uid();
  if v_role is distinct from 'admin' then
    raise exception 'Hanya admin yang boleh membuat postingan Update Web.';
  end if;
  if p_title is null or trim(p_title) = '' then
    raise exception 'Judul wajib diisi.';
  end if;

  if p_version is null then
    select version_major, version_minor, version_patch
      into v_major, v_minor, v_patch
    from public.update_web_posts
    order by version_major desc, version_minor desc, version_patch desc
    limit 1
    for update;

    if v_major is null then
      v_major := 1;
      v_minor := 0;
      v_patch := 0;
    else
      v_patch := v_patch + 1;
    end if;
  else
    if p_version !~ '^\d+\.\d+\.\d+$' then
      raise exception 'Format versi harus x.y.z (mis. 1.4.2).';
    end if;
    v_major := split_part(p_version, '.', 1)::int;
    v_minor := split_part(p_version, '.', 2)::int;
    v_patch := split_part(p_version, '.', 3)::int;
  end if;

  insert into public.update_web_posts (
    version_major, version_minor, version_patch,
    title, thumbnail_url, highlights, content, created_by
  ) values (
    v_major, v_minor, v_patch,
    trim(p_title), p_thumbnail_url, coalesce(p_highlights, '[]'::jsonb),
    coalesce(p_content, '{}'::jsonb), auth.uid()
  )
  returning * into v_row;

  return v_row;
exception
  when unique_violation then
    raise exception 'Versi tersebut sudah dipakai postingan lain.';
end;
$$;

grant execute on function public.create_update_web_post(text, text, jsonb, jsonb, text) to authenticated;

-- ============================================================
-- 4. RPC: add_update_web_post_discussion (SEMUA user login, bukan admin only)
-- ============================================================
--
-- Sama persis polanya dgn add_petty_cash_pengajuan_discussion (lihat
-- supabase/petty-cash-discussion-attachment-setup.sql) - komentar harus bisa
-- dikirim SEMUA user, tapi update langsung ke tabel update_web_posts dibatasi
-- admin only (lihat policy update di atas). RPC SECURITY DEFINER ini cuma
-- menyentuh kolom `discussions`, jadi aman dipakai semua user tanpa membuka
-- akses update penuh ke title/content/version lewat request mentah.

create or replace function public.add_update_web_post_discussion(
  p_id bigint,
  p_message text,
  p_content jsonb default null,
  p_mentions jsonb default '[]'::jsonb,
  p_attachment jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
begin
  if trim(coalesce(p_message, '')) = '' and p_content is null and p_attachment is null then
    raise exception 'Pesan tidak boleh kosong.';
  end if;

  select coalesce(nama, email, 'Unknown User') into v_name
  from public.profiles where id = auth.uid();

  update public.update_web_posts
  set discussions = coalesce(discussions, '[]'::jsonb) || jsonb_build_array(
    jsonb_build_object(
      'user_id', auth.uid(),
      'user_name', v_name,
      'message', p_message,
      'content', p_content,
      'mentions', coalesce(p_mentions, '[]'::jsonb),
      'attachment', p_attachment,
      'timestamp', now()
    )
  )
  where id = p_id;

  if not found then
    raise exception 'Postingan Update Web tidak ditemukan.';
  end if;
end;
$$;

grant execute on function public.add_update_web_post_discussion(bigint, text, jsonb, jsonb, jsonb) to authenticated;
