-- Rekening Bank untuk Petty Cash Reimbursement - user menyimpan 1+ rekening
-- pribadi di `user_bank_accounts` (dikelola dari halaman Profile & bisa
-- quick-add dari form Buat Petty Cash), lalu SNAPSHOT rekening yang dipilih
-- di-copy ke 3 kolom baru di `petty_cash_requests` saat submit tipe
-- "Reimbursement" - sama seperti pola snapshot petty_cash_voucher dari
-- petty_cash_pengajuan (lihat petty-cash-voucher-setup.sql). Karena snapshot,
-- GA/Finance yang review pengajuan cukup baca kolom di petty_cash_requests
-- (SELECT policy-nya sudah terbuka utk authenticated) - TIDAK perlu akses ke
-- tabel privat user_bank_accounts.
--
-- Jalankan SEKALI lewat SQL Editor Supabase (project utama).

create table if not exists public.user_bank_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  bank_name text not null,
  account_number text not null,
  account_holder_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_bank_accounts_user_id
  on public.user_bank_accounts (user_id);

create or replace function public.handle_user_bank_accounts_audit()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_at := old.created_at;
    new.updated_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists on_user_bank_accounts_write on public.user_bank_accounts;
create trigger on_user_bank_accounts_write
  before insert or update on public.user_bank_accounts
  for each row execute function public.handle_user_bank_accounts_audit();

alter table public.user_bank_accounts enable row level security;

-- Privat per-user - beda dari kebanyakan tabel petty cash lain yang
-- "select true for all authenticated" (dokumen bersama). Rekening bank adalah
-- data pribadi, jadi model policy-nya diambil dari notifications-setup.sql
-- (satu-satunya preseden tabel privat-per-user di repo ini), bukan dari tabel
-- petty cash lain.
drop policy if exists "user_bank_accounts_select_own" on public.user_bank_accounts;
create policy "user_bank_accounts_select_own"
  on public.user_bank_accounts
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "user_bank_accounts_insert_own" on public.user_bank_accounts;
create policy "user_bank_accounts_insert_own"
  on public.user_bank_accounts
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "user_bank_accounts_update_own" on public.user_bank_accounts;
create policy "user_bank_accounts_update_own"
  on public.user_bank_accounts
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_bank_accounts_delete_own" on public.user_bank_accounts;
create policy "user_bank_accounts_delete_own"
  on public.user_bank_accounts
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- Snapshot rekening di pengajuan Reimbursement - nullable, cuma keisi saat
-- type = 'Reimbursement'. Tidak perlu policy tambahan, SELECT
-- petty_cash_requests yang sudah ada otomatis mencakup kolom ini.
alter table public.petty_cash_requests
  add column if not exists bank_name text,
  add column if not exists bank_account_number text,
  add column if not exists bank_account_holder_name text;
